apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guarantee-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/seokheounjo/kub  # 실제 Git 저장소 URL로 변경 필요
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: guarantee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true