apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guarantee-project
  namespace: argocd
spec:
  description: Guarantee application project
  sourceRepos:
  - 'https://github.com/seokheounjo/kub'  # 실제 Git 저장소 URL로 변경 필요
  destinations:
  - namespace: guarantee
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: 'apps'
    kind: Deployment
  - group: 'networking.k8s.io'
    kind: Ingress